FROM scratch
LABEL maintainer="Roberto Ferranti <roberto@optionfactory.net>"
LABEL org.opencontainers.image.source=https://github.com/optionfactory/docker-machines

COPY deps/sloth-* /sloth

ENTRYPOINT ["/sloth"]
