FROM rockylinux/rockylinux:9
LABEL maintainer="Roberto Ferranti <roberto@optionfactory.net>"
LABEL org.opencontainers.image.source https://github.com/optionfactory/docker-machines

COPY deps/install-ps1.sh /etc/bash.bashrc
COPY deps/gosu-* /usr/local/bin/gosu