DELETE FROM mysql.user ;
DROP DATABASE IF EXISTS test ;
CREATE USER 'root'@'%' IDENTIFIED BY '';
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION ;
FLUSH PRIVILEGES ;